## Changes are required at 2 places. 1)PROJECT_NAME variable (line 8), 2)build steps(line 38) and 3)Update blackduck detect depth

stages:
  - sast_scan
  - blackduck_scan
variables:
  # PROJECT_NAME used for Checkmarx & BlackDuck scans. 
  PROJECT_NAME: "IPR_cognizant-intelligent-test-scripter"
  CxProject_Name: CxServer\Acc-IPReady\${PROJECT_NAME}
  COMMIT_ID: $(echo ${CI_COMMIT_SHA} | cut -c1-7)
  
sast_scan:
 image: codehub-docker.jfrog.io/devops-checkmarx:latest
 stage: sast_scan
 script:
  - /opt/CxConsolePlugin/runCxConsole.sh Scan -v 
   -CxServer "${CHECKMARX_SERVER}" 
   -Cxuser "${CHECKMARX_USER}" 
   -CxPassword "${CHECKMARX_PASSWORD}" 
   -ProjectName "${CxProject_Name}" 
   -LocationType folder  
   -LocationPath "${CI_PROJECT_DIR}" 
   -Preset "Cognizant Default Preset" 
   -executepackagedependency 
   -ReportPDF "$CI_PROJECT_DIR/${PROJECT_NAME}.pdf"
 rules:
  - if: '$CI_COMMIT_BRANCH =~ /sast\/.*/' 
 artifacts:
   paths:
    - "$CI_PROJECT_DIR/${PROJECT_NAME}.pdf"
blackduck_scan:
 stage: blackduck_scan
 image: cimg/openjdk:11.0.12-browsers
 script:
  # build steps. Update the blackduck detect depth accordingly
  - mvn -f pom.xml clean install -Dmaven.test.skip=true
  #blackduck commands
  - bash <(curl -s -L https://detect.synopsys.com/detect7.sh)
    --blackduck.url="${BLACKDUCK_URL}"
    --blackduck.api.token="${BLACKDUCK_TOKEN}"
    --detect.project.name="${PROJECT_NAME}"
    --detect.project.version.name="ver.1" 
    --logging.level.com.synopsys.integration=DEBUG 
    --detect.blackduck.signature.scanner.individual.file.matching=ALL 
    --blackduck.trust.cert=true
    --detect.risk.report.pdf=true  
    --detect.risk.report.pdf.path="report" 
    --detect.timeout=3600 
    --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING 
    --detect.detector.search.depth=0 
    --detect.excluded.directories=.git
 rules:
  - if: '$CI_COMMIT_BRANCH =~ /oss\/.*/'  
 artifacts:
  paths:
   - report/*.pdf
